### ISSUE TITLE
pyinside 코드 일부사용 관련

### ISSUE THREAD

**Issue by zza-ni** [geeksbaek/goinside#13]
작성하신 코드를 보면(d26e058a66ebb1d02b6294ad8c3cbeab21ff3bda)
GetAppID 함수 및 그 외 기타 소소한 부분들을 pyinside에서 착안해 가신 걸로 보입니다.
(app 인증 시, signature key 값 일치)

따라서, README.md 파일의 개요에 다음과 같은 내용을 추가해주시기를 바라는 바입니다.
감사합니다.

`[pyinside](https://github.com/jeongsj/pyinside)의 일부 기능을 참고하였습니다.`

**Comment by geeksbaek** [comment]
네 해당 사항을 반영하였습니다. 감사합니다. https://github.com/geeksbaek/goinside/commit/121346fd5ca4218a1ed5bb387b25bd4cd7d8c789

혹시 app_id를 가져오는 부분을 어떻게 찾으셨는지 알 수 있을까요? 공식 앱을 디컴파일 해 봐도 이 url로 요청을 보내는 코드를 찾을 수가 없어서요.
`https://dcid.dcinside.com/join/mobile_app_key_verification_3rd.php`
