### ISSUE TITLE
글 작성 시 "client_token" 이라는 값이 필요

### ISSUE THREAD

**Issue by geeksbaek** [geeksbaek/goinside#15]
글 작성 시 서버로 전송되는 multipart/form-data 값들 중에 "client_token" 라는 필드가 추가된 것으로 확인됩니다.

해당 값이 어떻게 생성되는지 역분석이 필요합니다.

**Comment by crux153** [comment]
앱 단에서 댓글 알림 등 푸시를 받기 위해 사용하는 FCM 토큰 값입니다. 푸시를 사용하지 않을 경우 "N"으로 두어도 상관 없는 것으로 보입니다.

**Comment by geeksbaek** [comment]
정보 감사합니다. 
client_token 필드가 글 작성에 실패하는 이유인 줄 알았는데 관계가 없었네요.
