### ISSUE TITLE
app id 생성 로직 분석

### ISSUE THREAD

**Issue by geeksbaek** [geeksbaek/goinside#17]
https://github.com/geeksbaek/goinside/issues/7 에 이은 이슈입니다.

디시인사이드 앱 구동 시 통신하는 SSL 패킷을 캡쳐해보면 아래와 같은 통신으로 app id를 받아오는 것을 확인할 수 있습니다.

```http
POST /join/mobile_app_key_verification_3rd.php HTTP/1.1
User-Agent: dcinside.app
Referer: http://www.dcinside.com
Content-Type: multipart/form-data; boundary=74026c88-9fe7-44b1-8916-48d9c907c769
Content-Length: 732
Host: dcid.dcinside.com
Connection: close
Accept-Encoding: gzip, deflate

--74026c88-9fe7-44b1-8916-48d9c907c769
Content-Disposition: form-data; name="value_token"
Content-Length: 64

c44fbecbdb970f4f2456272f33d22616da4d5248b450725d5d326b6c48e8bb6b
--74026c88-9fe7-44b1-8916-48d9c907c769
Content-Disposition: form-data; name="signature"
Content-Length: 44

ReOo4u96nnv8Njd7707KpYiIVYQ3FlcKHDJE046Pg6s=
--74026c88-9fe7-44b1-8916-48d9c907c769
Content-Disposition: form-data; name="pkg"
Content-Length: 16

com.dcinside.app
--74026c88-9fe7-44b1-8916-48d9c907c769
Content-Disposition: form-data; name="vCode"
Content-Length: 5

30054
--74026c88-9fe7-44b1-8916-48d9c907c769
Content-Disposition: form-data; name="vName"
Content-Length: 5

3.3.5
--74026c88-9fe7-44b1-8916-48d9c907c769--
```

위 요청에서 `value_token` 필드와 `signature` 필드가 필수 값입니다.

- `value_token` 필드는 https://github.com/geeksbaek/goinside/blob/eb6b132d0bfbca209f56cfe5123bdb12bd984233/auth.go#L49-L55 와 같이 생성되는 것으로 https://github.com/geeksbaek/goinside/issues/13 에서 확인했으나, 디시인사이드 앱 소스에서는 위 로직에 해당하는 코드를 아직 찾지 못했습니다.

- `signature` 필드는 고정 값으로 추측되지만 역시 난독화되어 있기 때문인지 소스에서 발견하지 못했습니다.

이후 혹시 모를 app id 생성 로직이 변경될 것에 대응하기 위해 이상 필드들의 생성 로직 분석이 필요합니다.

위 통신 이전에 선행되는 요청이 있는지도 확인해보았지만 의심되는 요청은 없는 것 같습니다. [이 화면](https://imgur.com/a/g5RB2oz)은 앱 최초 구동 후부터 `mobile_app_key_verification_3rd.php` 요청 전까지 php 서버와 통신한 내역입니다.

**Comment by crux153** [comment]
Java 소스만 디컴파일 해서는 안나옵니다. 동적 링크되는 lib/armeabi-v7a/libnative-lib.so 바이너리에서 value_token 값 생성이 이뤄지며, 디스어셈블러로 역분석 하시면 됩니다. signature 필드는 고정값입니다.
