### ISSUE TITLE
app_id를 받아올 수 없는 문제

### ISSUE THREAD

**Issue by JellyBrick** [geeksbaek/goinside#18]
반환 값 : `[{result: false, cause: "bad"}]`

**2019/10/25 14시경**부터 `app_id`를 얻어오는 코드가 작동하지 않습니다.

(공식앱 또한 `bad`를 띄웠으나, **15시경** 해결된 것으로 보입니다)

`app_id` 받아오는 부분에 변화가 생긴 것으로 추정됩니다.

[KotlinInside 관련 이슈 링크](https://github.com/organization/KotlinInside/issues/2)

**Comment by geeksbaek** [comment]
`value_token` 값의 구현 방식이 변경된 것 같습니다. 기존 구현 방식으로 생성한 `value_token`으로 요청을 보내면 실패하지만, 새 앱에서 생성된 `value_token` 값을 테스트 코드에 넣어 요청해보면 `app_id`가 정상 발급 됩니다.

테스트해보니 여전히 `value_token` 값이 시간 단위로 만료되는 것으로 보이는데, 기존 원문 구현 방식에서 추가 값이 들어간 것으로 추측됩니다.

`value_token` 값의 해싱 알고리즘은 여전히 SHA-256 인 것 같습니다.

기존과 다르게 발급 할 때마다 다른 `app_id`가 발급 되는 것으로 보아 발급 방식도 변경된 것 같습니다. (크게 중요한 변화는 아닌 것 같지만)

**Comment by JellyBrick** [comment]
@geeksbaek 해결했습니다.

[KotlinInside에서는 이렇게 해결하였습니다](https://github.com/organization/KotlinInside/blob/master/src/main/kotlin/be/zvz/kotlininside/security/Auth.kt#L73).

(`app_id` 값은 **12시간** 단위로 만료됩니다)
`yyyyMMddHH` 뒤에 *2019/5/30 0:0:0*부터 `app_id`가 몇 번 만료되었는지 카운트가 붙습니다.

예 : `yyyy MM dd HH count` = `2019 10 25 14 297`

추가로, 앱 실행시 GET 해오는 `app_check` JSON에서 `date` 값을 확인할 수 있었습니다.
이 `date` 값을 `yyyyMMddHH` + $count 대신 넣어도 동작합니다.

[참고하시면 좋을 것 같아요](https://github.com/organization/KotlinInside/blob/master/src/main/kotlin/be/zvz/kotlininside/security/Auth.kt#L47)

**Comment by JellyBrick** [comment]
> (`value_token` 값은 **12시간** 단위로 만료됩니다)
> `yyyyMMddHH` 뒤에 *2019/5/30 0:0:0*부터 `value_token`이 몇 번 만료되었는지 카운트가 붙습니다.

`yyyyMMddHH` 뒤에 붙는 카운트가 다시 변경된 듯 합니다.

정상적이라면 오후 2시인 지금, 카운트가 `299`여야 하나,
현재 (서버 기준) 카운트는 `298`입니다.

일단은 `(현재유닉스타임 - 1559142000) / (12 * 60 * 60)` 대신, 서버에서 값을 가져오도록 변경했고, 작동도 확인했습니다.

[해당 커밋](https://github.com/organization/KotlinInside/commit/e803ac79affec8fbe8195a0101be2e9dadc510db)

**Comment by geeksbaek** [comment]
https://github.com/geeksbaek/goinside/commit/d4fe0d27450122c03324e995f1c82c7d0f4a7d71 에서 반영하였습니다. 기여에 감사합니다.
