### ISSUE TITLE
could not fetch app id: 앱을 최신 버전으로 업데이트해주시기 바랍니다. 에러를 받아옵니다.

### ISSUE THREAD

**Issue by yusa-imit** [geeksbaek/goinside#21]
라이브러리로부터 해당 에러메시지를 받아옵니다.

무엇으로 이 에러를 해결 할 수 있습니까?

**Comment by JellyBrick** [comment]
organization/KotlinInside#9

**Comment by yusa-imit** [comment]
Ok, so goinside did not update yet. I'll use kotlin then. Thank you.
