### ISSUE TITLE
API 요청에 사용되는 app_id의 인증에 관한 문제

### ISSUE THREAD

**Issue by geeksbaek** [geeksbaek/goinside#7]
기존에는 app_id가 변하지 않는 값이었으나, 현재는 일정하지 않은 값이며 서버에서 어떠한 방식으로 유효성 검사를 거치는 것으로 확인되고 있다.

유효성 검사에 통과되지 않은 app_id로 요청을 보냈을 때 디시인사이드 서버는 다음과 같은 에러를 반환한다.

```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 09 Jul 2017 04:13:36 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 68
Connection: close
Set-Cookie: PHPSESSID=cb2ffb01c0u1u6be14dln27fv7; path=/; domain=.dcinside.com
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip

[{"result"   :   false, "cause"   : "certification"   }]
```

동적으로 생성되는 이 app_id는 길이가 62 Bytes로 고정되어 있으며, 다음은 현재까지의 추측이다.

- 3개의 구간으로 나누어져 있다. 모든 구간은 Base64 로 인코딩된 것으로 추측된다.
- 첫 번째 구간 (28 Bytes) 은  년월일 수준의 시간으로 생성된 해쉬값으로 추측된다. 매 12시간 전후로 변경되는 것으로 추측된다.
- 두 번째 구간 (30 Bytes) 은 기기에서 생성된 어떠한 랜덤한 값으로 추측된다. 매 12시간 전후로 변경되는 것은 첫 번째 구간과 동일하나, 앱을 재설치한 경우에도 변경되는 것으로 보아 랜덤하게 생성된 값, 혹은 밀리세컨드 단위 수준으로 측정된 시간으로 생성된 해쉬값으로 추측된다. 이 구간의 값을 임의로 변경해도 정상적으로 응답이 돌아오는 경우가 있는 것으로 보아, app_id를 서버에 등록하고 허가를 받은 구조는 아닌 것 같다.
- 세 번째 구간 (4 Bytes) 은 생략해도 상관없는 쓰레기 값으로 추측된다. 실제로 해당 구간을 삭제한 후 요청을 보내도 정상적으로 응답이 돌아온다.

다음은 수집된 app_id 샘플들이다.

```
NXpoTmRTeWZWMFFNUGxJSE9CTThSbHo2OVNYQTh2MWVSdzA1bEM3NHA1OD0%3D
TDRhVlRQVmI4ZHZ6RVBNcHJzRlkzdlMySjlVODRwM0pWeXZzMmtaYWROaz0%3D
TDRhVlRQVmI4ZHZ6RVBNcHJzRlkzdVhISXRtaW9BMURCNjJGUWtLcitmaz0%3D
c2MwMHBaZEZmRHZJTFpKWXRFMmt4U3ZHTmRqRms2S0pJRGRFb0JLcEplbz0%3D
VTZsS001aE1JWnZCNURaSXZXQzk0MlhMUE1yeS9kNXNIclNxZENyUmR4bz0%3D
VTZsS001aE1JWnZCNURaSXZXQzk0d0wzYWpOakV2UDlFeEp0ZVNiYTd6Zz0%3D
VTZsS001aE1JWnZCNURaSXZXQzk0NkRLVU5naExZTFJQQWcwR2hzT1lETT0%3D
VTZsS001aE1JWnZCNURaSXZXQzk0OWpXcEF3ZGJVSmcvWFE3OU1TSXZqOD0%3D
OUlQbjhGSlFqalVObjZHcDRPVWpQRUVQdDFrTHZvZEFjd2tiWW1FejNrTT0%3D
```

**Comment by crux153** [comment]
DC Life의 app_id인 SEMwMFcxYUpsU0Z1cUVidDQvbXV5QT09를 사용하면 아직 정상적으로 동작합니다.

변경된 공앱 app_id 생성 방법도 알고는 있으나 또 막힐 것 같으므로 일단 디랖 app_id로 변경하여 Pull Request #8 로 올려두었으니 확인해주세요.

**Comment by geeksbaek** [comment]
기여에 감사합니다. https://github.com/geeksbaek/goinside/commit/f8aff9b256682ab5695ca0e0ae99bbaf02c95535 로 머지했습니다.

머지하면서 gallog 서브패키지에서 goinside 패키지를 ".."으로 import하는 부분이 travis 빌드에서 오류를 일으켜서 그 라인만 원래대로 돌렸습니다.

app_id 생성 방법을 어떻게 아셨는지 알 수 있을까요?

**Comment by crux153** [comment]
역분석했습니다. 그리고 변경된 app_id는 기기에서 생성되는 것이 아니라 서버에서 받아오는 구조입니다.

**Comment by geeksbaek** [comment]
그런가요? 저는 패킷 잡아서 봐도 api 요청할 때 app_id가 base64 인코딩되서 서버로 먼저 보내지는 것만 확인이 되네요..

**Comment by geeksbaek** [comment]
https://github.com/Jeongsj/pyinside/blob/master/protocol.py#L9-L20

위 코드를 참고하여 GetAppID 함수를 구현하였습니다. https://github.com/geeksbaek/goinside/commit/d26e058a66ebb1d02b6294ad8c3cbeab21ff3bda
